# get all items
GET http://localhost:4322/api/items

# get item by query
GET http://localhost:4322/api/items?q=smart

# get item by id
GET http://localhost:4322/api/items/2

# get item by id, false id
GET http://localhost:4322/api/items/patata
